### ISSUE TITLE
Settings do not load

### ISSUE THREAD

**Issue by FivosM** [grcrt/grcrt-script#1]
## Description
when I click GRCRTools -> "Settings" nothing happens

## How to reproduce the problem
  - git clone https://github.com/grcrt/grcrt-script
  - cd grcrt-script
  - npm run build
```
> grcrt@0.0.0-development build /home/fivos/1-build/grcrt-script
> node bin/build.js

./tmp/GRCRTLangs.js created
./tmp/common.js created
./tmp/modules.js created

```
  - Copy `tmp/GrepolisReportConverterV2.user.js` code to "New user script" in greasemonkey

## Expected behaviour
Settings should load the settings window

## Actual behaviour
when I click GRCRTools -> "Settings" nothing happens

## How often
Always

## Additional information
  - Works when downloaded from the website and not created locally
  - Script version: Latest from github (v4.0.0)
  - Operating system: Ubuntu 16.04.4 LTS
  - Used web-browser: Firefox

By the way, here is my [GrepolisReportConverterV2.user.js](https://gist.github.com/FivosM/221661a2c7b40de72d02596b532f8a9f)

**Comment by tomaski** [comment]
OK, I can confirm that this is not expected. We'll take a look why it goes wrong. In the meantime, as a workaround, to get your builds working, you can use
```
$ npm run build
$ npm run test
$ npm run dist
```
resulting script will be found in `dist\`. 
> **NOTE:** it will be a compiled version, just like the one we release

**Comment by FivosM** [comment]
Works using these commands, thanks.

**Comment by FivosM** [comment]
This did not resolve the issue for me, still compiling the js.
