### ISSUE TITLE
Command list movement bug

### ISSUE THREAD

**Issue by tudela96** [grcrt/grcrt-script#14]
## Description
After the last update, taking out the command list window doesn't let me cancel the attack or see the time that the attack arrives before three or four seconds.

## How to reproduce the problem
  - Send attack/reinforcements/spies
  - Drag cursor to the sended attack on command list
 

## Expected behavior
I should be able to cancel the attack immediately when pressing the X or see the time when the attack arrives at the first try

## Actual behavior
when having the command list out of his standard place, the action cant be cancelled correctly before 3 or 4 seconds

## How often
[Only happens when the command list is moved out of his standard place]

## Additional information
  - Script version: [5.0.1]
  - Operating system: [Windows 10 home version 1803]
  - Used webbrowser: [Chrome Versión 66.0.3359.181 (Build oficial) (64 bits)]

**Comment by tomaski** [comment]
I can't reproduce the described issue. Could you please open Console (`Ctrl`+`Shift`+`J`) and see if any errors / warning appear when you try to cancel the attack?

Also, do you have any other scripts? If so, which ones?

**Comment by tudela96** [comment]
Those errors and messages on the console show up when i open the game, but no errors appear when i cancel the action.
Only grepolis report converter is activated in this gif

![command list bug](https://user-images.githubusercontent.com/39446279/40279906-727806a0-5c4b-11e8-85ec-5e7245c9f3d4.gif)

As you can see the time doesnt display  and i have to click many times the X to cancel it.
I have also tried it on firefox and happens the same.
i've been talking to my mates and nobody else seems to have this problem with the same extension

**Comment by tomaski** [comment]
What firewall / antivirus / adblocker are you using? Do you have any other "web safety" tools installed? What about browser addons (any addon that you have both on FF and Chrome)?

**Comment by tudela96** [comment]
Im using Windows Defender. Adblock Plus, Pop up blocker for Chrome™ - Poper Blocker, and Tampermonkey on Chrome. And only Tampermonkey on Firefox with Grepolis Report Converted installed on both browsers.
