### ISSUE TITLE
Sound absent

### ISSUE THREAD

**Issue by imdopey** [grcrt/grcrt-script#27]
## Description
Whenever i get attacked the custom sound doesn't play. Even trying to test the sound function doesn't give anything. I made sure the sound was OK since the normal since i attacked myself without add on and grepolis sound on.

## How to reproduce the problem
  - Get attacked
  - No sound comes out
  - Go to settings and test a new sound
  - No sound comes out

## Expected behavior
When i get attacked it should play the custom set sound which was provided via a Youtube link.

## Actual behavior
It gives a notification that its playing the sound.. however it emits nothing.

## How often
Always; tested on 2 worlds

## Additional information
  - Script version: [5.0.6]
  - Operating system: [Win 10]
  - Used webbrowser: [Chrome]

**Comment by tomaski** [comment]
Hi @imdopey ! thank you for taking time to report this issue. We'll go and check it out

**Comment by imdopey** [comment]
thanks for taking the time; i really appreciate the function and work put into the tool :D
