### ISSUE TITLE
Chrome becomes slow when using the map

### ISSUE THREAD

**Issue by rbesland** [grcrt/grcrt-script#33]
## Description
When using any webbowser based on webkit, the map becoming very slow and the interface very unresponsive?

## How to reproduce the problem
Use the Grepolis Report Converter script with Tampermonley on Chrome, Vivaldi, Opera or Chromium

## Expected behavior
No problem on Firefox, the map and the interface are all ok.

## Actual behavior
All the interface become very slow and unusable.

## How often
Always

## Additional information
  - Script version: Latest 5.0.7
  - Operating system: Windows 10 1903 up to date
  - Used webbrowser: Any webbrowser based on webkit (Chrome, Chromium, Vivaldi, Opera)

## What I have already tested
- Tested on multiple webbrowser : no problem only on Firefox (tampermonkey & greasemonkey no problems)
- Tested on another PC : same issue
- Tested on another PC on Linux : same issue
- Tested with an extension like "User Agent Switcher" to set the user-agent of Firefox but same issue

**Comment by rbesland** [comment]
It seems that the problem is more noticeable when using the GRCR script, but even without it the game becomes very slow after some time of use.
You can close this issue, I don't think this is related to the script.

**Comment by tomaski** [comment]
I use Chrome as my main browser and didn't experience the issues you described. But, on the other hand, my PC is quite powerful.... please let us know if you find out it that it is, in fact, GRCRT that is causing the slowdowns. 
Thank you for taking the time to reach out :)

**Comment by rbesland** [comment]
Finally, like I said in my last reply, I don't think this issue is caused by the GRCRT script. But I have a quite powerful PC too, brand new for some latest games (CPU i7 12 cores, GTX 2080, 32GB RAM DDR4...). I don't think the slowness is caused by any lack of power.

I'll try to find out what happens and will be back here to tell you if I found something or not.
Thank you for taking the time to answer me :)
