### ISSUE TITLE
Disable alarm for selected players 

### ISSUE THREAD

**Issue by dani3390** [grcrt/grcrt-script#59]
## Description
Sometimes it happens that some players create new accounts (or even use their real ones) just to fake attacks all night to trigger the alarm, and this is really annoying, since you are costricted to just switch off it with the danger of getting real attacks
So I was hoping that you could add an option, if possibile, where on every line (like the emoji one) there's the name of a player for that server that just disables the alarm from triggering on so that fake attacks are useless.
Obviously this is just an advice, but I'm pretty sure that it could be useful for a lot of person (if it's possibile to implement it)

**Comment by tomaski** [comment]
thank you for taking the time to open that issue. We will look into and see if we can integrate it :)
